---
title: "Tottenham Hotspur F.C. sub-Reddit (r/coys) Sentiment Analysis"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
    theme:
      bootswatch: "cosmo"
runtime: shiny
---
```{r setup, include=FALSE, context='server'}
library(flexdashboard)
library(shiny)
library(bslib)

library(dplyr)
library(plotly)

# Read data
combined_data <- read_rds('combined_data.rds')
comments <- read_rds('comments.rds')

```


Dashboard
=======================

Sidebar {.sidebar}
-----------------------

**Pick a thread type to explore the sentiment score in the interactive graph!**
```{r}

# Thread choose
radioButtons(inputId = 'thread_type', label = '',
             choiceNames = c('Match Thread', 'Post-Match Thread', 'Daily Discussion'), 
             choiceValues = c('match', 'post_match', 'daily'),
             selected = 'match')

# Render text accordingly
renderText({
  
  if (input$thread_type == 'match') {
    'Match Threads are where ongoing live matches are discussed as they occur. Discussion usually starts right before the kick-off and ends at the final whistle. \n Each bar indicates a thread that is dedicated to a match. Click on any thread to explore the comments!'
  } else if (input$thread_type == 'post_match') {
    'Post-Match Threads are where concluded matches are discussed. Discussion usually starts right after the final whistle and lasts for several hours. \n Each bar indicates a thread that is dedicated to a match. Click on any thread to explore the comments!'
  } else {'Daily Threads are where everyday general discussion takes place. Discussion is always ongoing and there is a new thread every day. \n In this graph, thick bars indicate a daily discussion threads that occured on the same day as a match, narrow bars indicate threads that did not had a match the same day.'}
  
  
})

```

Want to know more about how the sentiment score was calculated and the methodology? Click the **'About'** button on the navigation bar!

Row {data-height=115}
-----------------------
### Average Win Sentiment {.value-box}

```{r}
renderValueBox({
  
  sentiment_win <- mean(combined_data$mean_sentiment[combined_data$thread_type == input$thread_type & combined_data$win == 'Win'])

  
  valueBox(value = round(sentiment_win, digits = 3),
           icon = 'ion-android-happy',
           color = '#14B358')
})

```

### Average Win Polarity (Sentiment SD) {.value-box}

```{r}
renderValueBox({
  
  polarity_win <- mean(combined_data$polarity[combined_data$thread_type == input$thread_type & combined_data$win == 'Win'])

  
  valueBox(value = round(polarity_win, digits = 3),
           icon = 'ion-arrow-swap',
           color = '#14B358')
})

```

### Average Win Comment Word Count {.value-box}

```{r}
renderValueBox({
  
  words_win <- mean(combined_data$mean_words[combined_data$thread_type == input$thread_type & combined_data$win == 'Win'])

  
  valueBox(value = round(words_win, digits = 3),
           icon = 'ion-chatbubbles',
           color = '#14B358')
})

```

Row {data-height=115}
-----------------------
### Average Lose Sentiment {.value-box}

```{r}
renderValueBox({
  
  sentiment_win <- mean(combined_data$mean_sentiment[combined_data$thread_type == input$thread_type & combined_data$win == 'Lose'])

  
  valueBox(value = round(sentiment_win, digits = 3),
           icon = 'ion-android-sad',
           color = '#CE3323')
})

```

### Average Lose Polarity (Sentiment SD) {.value-box}

```{r}
renderValueBox({
  
  polarity_win <- mean(combined_data$polarity[combined_data$thread_type == input$thread_type & combined_data$win == 'Lose'])

  
  valueBox(value = round(polarity_win, digits = 3),
           icon = 'ion-arrow-swap',
           color = '#CE3323')
})

```

### Average Lose Comment Word Count {.value-box}

```{r}
renderValueBox({
  
  words_win <- mean(combined_data$mean_words[combined_data$thread_type == input$thread_type & combined_data$win == 'Lose'])

  
  valueBox(value = round(words_win, digits = 3),
           icon = 'ion-chatbubbles',
           color = '#CE3323')
})

```

Row {data-height=770}
-----------------------
### r/coys Average Reddit Thread Sentiment {data-width=650}

```{r main_plot}
renderPlotly({

  if (input$thread_type != 'daily') {  
  
  plot_data <- combined_data |> 
    filter(thread_type == input$thread_type)
    
    plot <- plot_data |>
      ggplot(aes(x = date,y = mean_sentiment, text = paste0('Date: ', date, '\n', 
                                                            'Match: ',score_label, '\n', 
                                                            'Sentiment: ', mean_sentiment))) +
        geom_hline(yintercept = 0, color = 'black') +
        geom_segment(aes(yend = 0, xend = date, color = win),
                       lineend = "round",
                       size = 1.5) +
        geom_point(aes(y = mean_sentiment, color = win),
                     size = 3) +
        
        scale_color_manual(values = c("#14B358", "#1A7FC2", "#CE3323")) +
        scale_y_continuous(limits = c(-0.2, 0.4)) +
        
        labs(
             title = "",
              y = "Average sentiment",
              x = "Date",
              color = "Game outcome") +
        theme(text = element_text(family = "Candara", size = 16),
              legend.position = "bottom",
              axis.title.x = element_blank(),
              axis.text.x = element_blank(),
              axis.ticks.x = element_blank()
          ) +
      theme_minimal()

    }
  
    else{
    
    plot_data <- combined_data |> 
      filter(thread_type == "daily")
  
    plot <- plot_data |> 
      ggplot(aes(x = date, y = mean_sentiment, text = ifelse(matchday == 1, 
                                                             paste0('Date: ', date, '\n', 
                                                             'Match: ',score_label, '\n', 
                                                             'Sentiment: '),
                                                             paste0('Date: ', date)))) +
      geom_hline(yintercept = 0, color = 'black') +

      geom_segment(aes(yend = 0, xend = date, color = win, size = matchday),
                   lineend = "round") +

      scale_color_manual(values = c("#14B358", "#1A7FC2", "#CE3323")) +
      scale_size_manual(values = c(0.1, 1)) +
      scale_y_continuous(limits = c(-0.2, 0.4)) +

      
      labs(title = "",
              y = "Average sentiment",
              x = "Date",
              color = "Game outcome") +
      theme(text = element_text(family = "Candara", size = 16),
            legend.position = "bottom",
            axis.title.x = element_blank(),
            axis.text.x = element_blank(),
            axis.ticks.x = element_blank()
      ) +
      theme_minimal()
            
    
  }

  
  ggplotly(plot, tooltip = 'text', source = 'main_plot') %>% 
    layout(legend = list(orientation = 'h')) %>%
    layout(annotations = list(x = 1, y = 1, text = "Click on any thread data point to open the comment explorer", 
      showarrow = F, xref = 'paper', yref = 'paper', 
      xanchor = 'right', yanchor = 'auto', xshift = 0, yshift = 0,
      font = list(size = 15, color = "black")))
  
})
  
```

### Comment Explorer {data-width=350}

```{r comment_table}

renderDataTable(options = list(pageLength = 10,
                 dom = "t"),{

  clickData <- event_data("plotly_click", source = "main_plot")
   if (is.null(clickData)) return(NULL)

  click_y <- clickData[["y"]]
  
  thread_url <- combined_data |> 
    filter(thread_type == input$thread_type) |> 
    filter(mean_sentiment == as.numeric(click_y) | polarity == as.numeric(click_y))

  df <- comments |>
    filter(url == thread_url$url[1]) |>
    select("Upvotes" = score, "Comment" = comment) |> 
    arrange(desc(Upvotes))

  df
})


```
